language: python

python:
    - 2.6
    - 2.7

env:
    - JSON=simplejson
    - JSON=json

install:
    - python setup.py install
    - pip install -r requirements-test.txt --use-mirrors
    - pip install -r requirements-$JSON.txt --use-mirrors

script:
    - trial test_stimpy
